title: Ayşe Nur Zengin
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://aysenurzengin.github.io
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Ana Sayfa
    url: /index.html
  - title: Ben Kimim?
    url: /about
  - title: İletişim
    url: /contact

social:
  github: aysenurzengin
  twitter: zenginaysee
  facebook: aysenur.zengin.1829
  email: aysezengin96@gmail.com

google_analytics: "UA-58263416-1"
